# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 445)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.getDataGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.getDataGroup.setGeometry(QtCore.QRect(10, 20, 621, 111))
        self.getDataGroup.setObjectName("getDataGroup")
        self.layoutWidget = QtWidgets.QWidget(self.getDataGroup)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.type = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.type.setContentsMargins(0, 0, 0, 0)
        self.type.setObjectName("type")
        self.yearly = QtWidgets.QRadioButton(self.layoutWidget)
        self.yearly.setChecked(True)
        self.yearly.setObjectName("yearly")
        self.type.addWidget(self.yearly)
        self.monthly = QtWidgets.QRadioButton(self.layoutWidget)
        self.monthly.setObjectName("monthly")
        self.type.addWidget(self.monthly)
        self.daily = QtWidgets.QRadioButton(self.layoutWidget)
        self.daily.setObjectName("daily")
        self.type.addWidget(self.daily)
        self.splitter_2 = QtWidgets.QSplitter(self.getDataGroup)
        self.splitter_2.setGeometry(QtCore.QRect(510, 20, 100, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.el = QtWidgets.QLabel(self.splitter_2)
        self.el.setObjectName("el")
        self.endDate = QtWidgets.QDateEdit(self.splitter_2)
        self.endDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2014, 9, 1), QtCore.QTime(0, 0, 0)))
        self.endDate.setObjectName("endDate")
        self.URL = QtWidgets.QTextEdit(self.getDataGroup)
        self.URL.setGeometry(QtCore.QRect(10, 50, 521, 41))
        self.URL.setObjectName("URL")
        self.splitter = QtWidgets.QSplitter(self.getDataGroup)
        self.splitter.setGeometry(QtCore.QRect(390, 20, 100, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.sl = QtWidgets.QLabel(self.splitter)
        self.sl.setObjectName("sl")
        self.startDate = QtWidgets.QDateEdit(self.splitter)
        self.startDate.setDateTime(QtCore.QDateTime(QtCore.QDate(1995, 9, 1), QtCore.QTime(0, 0, 0)))
        self.startDate.setObjectName("startDate")
        self.GetData = QtWidgets.QPushButton(self.getDataGroup)
        self.GetData.setGeometry(QtCore.QRect(540, 50, 71, 41))
        self.GetData.setObjectName("GetData")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 621, 81))
        self.groupBox.setObjectName("groupBox")
        self.Generate = QtWidgets.QPushButton(self.groupBox)
        self.Generate.setGeometry(QtCore.QRect(540, 32, 71, 41))
        self.Generate.setObjectName("Generate")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label = QtWidgets.QLabel(self.splitter_3)
        self.label.setObjectName("label")
        self.Dataname = QtWidgets.QLineEdit(self.splitter_3)
        self.Dataname.setObjectName("Dataname")
        self.oneKey = QtWidgets.QPushButton(self.centralwidget)
        self.oneKey.setGeometry(QtCore.QRect(10, 360, 621, 41))
        self.oneKey.setObjectName("oneKey")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 621, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Output = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.Output.setGeometry(QtCore.QRect(10, 20, 601, 81))
        self.Output.setObjectName("Output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CEIC爬虫"))
        self.getDataGroup.setTitle(_translate("MainWindow", "获取数据"))
        self.yearly.setText(_translate("MainWindow", "年数据"))
        self.monthly.setText(_translate("MainWindow", "月数据"))
        self.daily.setText(_translate("MainWindow", "日数据"))
        self.el.setText(_translate("MainWindow", "止"))
        self.sl.setText(_translate("MainWindow", "起"))
        self.GetData.setText(_translate("MainWindow", "获取数据"))
        self.groupBox.setTitle(_translate("MainWindow", "生成XLSX"))
        self.Generate.setText(_translate("MainWindow", "生成"))
        self.label.setText(_translate("MainWindow", "数据名称"))
        self.oneKey.setText(_translate("MainWindow", "一键获取并生成"))
        self.groupBox_2.setTitle(_translate("MainWindow", "输出信息"))
